### ISSUE TITLE
Add instructions to find default gateway for edge cases.

### ISSUE THREAD

**Issue by UpstreamData** [econoalchemist/COLDCARD-BlackBox#1]
In the file 03-SlushPool.md, while talking about finding the IP address of the miner, you talk about accessing your router's web interface to view connected devices, it might be a good idea to demonstrate how to find your default gateway which is usually the IP of your router.  I like to do this by opening Command Prompt on windows, running the command ```ipconfig```, then searching through to find the default gateway, but there are other options.

**Comment by econoalchemist** [comment]
Added with this commit: https://github.com/econoalchemist/COLDCARD-BlackBox/commit/53f714cfae2b42a926e33458dc40060464b3b95f
