### ISSUE TITLE
Add additional ASIC specific scanning tool links.

### ISSUE THREAD

**Issue by UpstreamData** [econoalchemist/COLDCARD-BlackBox#2]
In the file 03-SlushPool.md, you reference Angry IP as a scanning tool, it might be a good idea to reference some ASIC specific tools such as BTCTools, as they are much easier to use for identifying ASICs. BTCTools Download Link - https://url.btc.com/btc-tools-download BTCPool Tools - https://pool.btc.com/tools

**Comment by econoalchemist** [comment]
Added with this commit: https://github.com/econoalchemist/COLDCARD-BlackBox/commit/53f714cfae2b42a926e33458dc40060464b3b95f
